const {launch}=require('./audit-browser.cjs')
const assert=require('node:assert/strict')
const fs=require('node:fs')
;(async()=>{const b=await launch();const checks=[];const ok=s=>{checks.push(s);console.log('PASS',s)};try{
 await b.viewport(1440,900);await b.open('/login');await b.click('.language-switcher__option[lang="en"]');await b.evaluate(`(async()=>{window.qaModule=await import('/scripts/validation/frontend-state-fixture.js');window.cleanupQa=window.qaModule.mount()})()`);await b.until('Boolean(window.setAuditFixture)');
 const state=async value=>{await b.evaluate(`window.setAuditFixture(${JSON.stringify(value)})`);await b.wait(150)}
 for(const tier of ['free','pro']){await state({kind:'plan',payload:{tier,used:12,limit:50}});assert.match(await b.evaluate(`document.querySelector('#audit-fixture').innerText`),new RegExp(tier,'i'))}ok('Free and Pro plan presentation')
 await state({kind:'plan',payload:{tier:'free',used:50,limit:50},limitReached:true});assert.equal(await b.evaluate(`document.querySelector('#audit-fixture textarea').disabled`),true);ok('Quota reached disables composer')
 await state({kind:'plan',payload:{tier:'free',used:0,limit:0},limitReached:true});assert.match(await b.evaluate(`document.querySelector('#audit-fixture').innerText`),/limit/i);ok('Zero quota is exhausted, not unlimited')
 await state({kind:'proposal'});assert.equal(await b.evaluate(`document.querySelector('.ai-proposal__apply').disabled`),true);await b.click('.ai-proposal__preview-action');assert.equal(await b.evaluate(`document.querySelector('.ai-proposal__apply').disabled`),false);await b.click('.ai-proposal__apply');assert.equal(await b.evaluate('window.auditApplied'),true);await b.click('.ai-proposal__reject');assert.equal(await b.evaluate('window.auditRejected'),true);ok('Proposal preview gates Apply; Apply and Reject callbacks work')
 await state({kind:'proposal',context:{}});assert.equal(await b.evaluate(`document.querySelector('.ai-proposal__apply').disabled`),true);ok('Missing context blocks Apply')
 await b.evaluate('window.qaModule.enableHookFixtures()');await state({kind:'hook'});await b.until('Boolean(window.auditAi && !window.auditAi.isLoading)');assert.equal(await b.evaluate('window.auditAi.messages.length'),1);assert.equal(await b.evaluate('window.auditAi.conversationList.length'),1);await b.click('#qa-new');assert.equal(await b.evaluate('window.auditAi.messages.length'),0);assert.equal(await b.evaluate('window.auditAi.activeConversationId'),null);assert.equal(await b.evaluate('window.auditAi.conversationList.some(x=>x.isActive)'),false);ok('History loads; new conversation clears current thread')
 await b.fill('#audit-fixture #ai-prompt','Improve the hero copy.');await b.click('#audit-fixture .ai-composer button[type=submit]');await b.until('Boolean(document.querySelector(".ai-send-error"))');assert.equal(await b.evaluate('window.auditAi.draft'),'Improve the hero copy.');await b.click('.ai-send-error__retry');await b.until('!window.auditAi.isSending');assert.equal(await b.evaluate('window.auditAi.messages.length'),0);ok('Send error and retry retain draft; no invented reply')
 await b.evaluate('window.auditAi.selectConversation("qa-thread")');await b.wait(180);await b.click('.ai-proposal__preview-action');await b.click('.ai-proposal__apply');await b.wait(180);assert.equal(await b.evaluate('window.auditAi.proposals[0].status'),'pending');ok('Failed Apply remains pending')
 await b.evaluate('window.qaModule.permitFixtureApply()');await b.click('.ai-proposal__apply');await b.wait(180);await b.click('#qa-undo');assert.ok(await b.evaluate('Boolean(window.auditAi.undoNotice)'));ok('Undo foundation reports backend dependency')
 for(const section of ['users','websites','templates','billing','domains','notifications','support','audit']){await state({kind:'admin',section,rows:[{id:'qa',name:'QA fixture '+('long '.repeat(25)),title:'QA test notification',email:'test@example.invalid',role:'user',status:'active',owner:{name:'QA Owner'},domain:'test.example.invalid',subject:'QA support',action:'Updated site',actor:'QA Admin',updatedAt:'2026-10-08T12:00:00Z'}]});for(const [width,height] of [[1440,900],[834,1112],[390,844]]){await b.viewport(width,height);assert.equal(await b.evaluate('document.documentElement.scrollWidth>innerWidth+1'),false)}}ok('Every admin table with populated, long-content fixtures at three sizes')
 for(const status of ['loading','empty','error','unavailable']){await state({kind:'admin',section:'users',status});assert.ok(await b.evaluate(`document.querySelector('#audit-fixture').innerText.length>20`))}await state({kind:'admin',section:'users',status:'error'});await b.click('#audit-fixture button');assert.equal(await b.evaluate('window.auditRetried'),true);ok('Admin loading, empty, unavailable, error and retry states')
 await b.evaluate('window.cleanupQa()');assert.deepEqual(b.errors,[]);ok('No fixture console errors')
 }finally{fs.writeFileSync('artifacts/frontend-audit/states.json',JSON.stringify({checks,errors:b.errors},null,2));b.close()}})().catch(e=>{console.error(e);process.exitCode=1})
