import { createBlock, createPage, createSection, normalizeEditorDocument, buildMenuFromDocumentPages, createLocalDraftDocument } from '@/models/siteEditor'
import { getTemplatePageSkeletons } from '@/models/siteTemplate'
import { createStarterForm } from '@/models/siteForm'
import { translate } from '@/i18n/dictionary'

// Authored sample content, not generated by AI. Only requested by the demo service.
export function createDemoWebsite(site) {
  const t = (key, values) => translate(key, document.documentElement.lang, values)
  if (site.id !== 'demo-website') return {
    ...createLocalDraftDocument({ t, pageSkeletons: getTemplatePageSkeletons(site.templateId).map(page => ({ ...page, name: t(page.nameKey) })) }),
    siteId: site.id,
  }
  const heading = (text, size = 32) => createBlock('heading', { content: { text }, style: { fontSize: size, fontWeight: 700 } })
  const text = copy => createBlock('text', { content: { text: copy }, style: { fontSize: 17 } })
  const section = (title, blocks, type = 'custom', background = 'surface') => ({
    ...createSection(type, { style: { padding: 48, maxWidth: 1120, background }, blocks: [heading(title), ...blocks] }),
    name: title,
  })
  const home = createPage({ name: 'Home', slug: '', sections: [
    section('Less busywork. More momentum.', [
      text('Orbit brings your projects, customer conversations and next steps into one calm workspace. A sample SaaS website built in the visual editor.'),
      createBlock('button', { content: { label: 'Explore Orbit', href: '/about' } }),
    ], 'hero', 'accent-soft'),
    section('Everything your team needs to move forward', [
      heading('One shared view', 22), text('Keep project milestones and ownership clear, from kickoff to delivery.'),
      heading('Useful automation', 22), text('Turn repeatable steps into workflows so your team can focus on thoughtful work.'),
      heading('Customer context', 22), text('Bring conversations and project notes together before your next meeting.'),
    ], 'features'),
    section('Services that meet you where you are', [
      text('Workspace setup · Workflow design · Team onboarding'),
      text('Start with a guided setup, then shape a workspace around the way your team works.'),
    ]),
    section('Simple plans for growing teams', [
      heading('Starter · $19 / month', 22), text('Sample plan: a focused workspace for independent teams.'),
      heading('Team · $49 / month', 22), text('Sample plan: shared workflows and collaboration for growing teams. Illustrative pricing only; checkout is not connected.'),
    ], 'custom', 'accent-soft'),
    section('A clearer working day', [
      text('“Our next steps finally have a home, and everyone knows what comes next.”'),
      text('Illustrative testimonial · Sample customer, not a verified review.'),
    ], 'testimonials'),
    section('Frequently asked questions', [
      heading('Can we start with one project?', 22), text('Yes. Shape one workflow first, then use what you learn to expand.'),
      heading('Is this a live service?', 22), text('This is an editable demo website. No subscription, messages or customer data are sent.'),
    ]),
    section('Let’s talk about your next project', [
      text('Tell us what your team is working on. This preview form does not send messages.'),
      createBlock('form', { content: { form: createStarterForm(t) } }),
    ], 'contact'),
    section('Orbit', [text('A little more clarity. A lot more possibility.'), text('Demo website · All content is illustrative.')], 'footer'),
  ] })
  const about = createPage({ name: 'About', slug: 'about', sections: [
    section('Good work starts with clarity', [text('Orbit is a fictional technology company exploring a simpler way for small teams to collaborate.')], 'hero'),
    section('Built around people', [text('Clear ownership. Considered tools. Space to do your best work.')], 'features'),
    section('Start a conversation', [text('Explore the contact form on Home to test the frontend experience.')], 'footer'),
  ] })
  return buildMenuFromDocumentPages(normalizeEditorDocument({ siteId: site.id, isLocalDraft: true, pages: [home, about], activePageId: home.id }))
}
